server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro1?serverTimezone=CTT&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: true  #设置开启热部署
mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.imooc.shiro.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

